version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  api:
    build: .
    container_name: book-api
    ports:
      - "5005:5000"
    depends_on:
      - mongo
    volumes:
      - .:/app

volumes:
  mongo-data:
